// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package querier

import (
	"time"
)

type Transaction struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	Status        string    `json:"status"`
	Type          string    `json:"type"`
	Balance       float64   `json:"balance"`
	ReferenceID   string    `json:"reference_id"`
	TransactionAt time.Time `json:"transaction_at"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type User struct {
	ID        string    `json:"id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Wallet struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Status    string    `json:"status"`
	Balance   float64   `json:"balance"`
	EnabledAt time.Time `json:"enabled_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
