// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package querier

import (
	"context"
)

type Querier interface {
	CheckWalletExists(ctx context.Context, userID string) (bool, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	FindTokenByUserId(ctx context.Context, token string) (User, error)
	FindTransactionByUserId(ctx context.Context, userID string) ([]Transaction, error)
	FindUser(ctx context.Context, id string) (User, error)
	FindWalletByUserId(ctx context.Context, userID string) (Wallet, error)
	UpdatBalanceWalletByUserId(ctx context.Context, arg UpdatBalanceWalletByUserIdParams) (Wallet, error)
	UpdateWalletByUserId(ctx context.Context, arg UpdateWalletByUserIdParams) (Wallet, error)
}

var _ Querier = (*Queries)(nil)
